USE [ZorgApp]
GO
/****** Object:  Table [dbo].[Arts]    Script Date: 13-2-2025 17:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Arts](
	[ID] [int] NOT NULL,
	[Naam] [nvarchar](50) NOT NULL,
	[Specialisatie] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Arts] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_Arts] UNIQUE NONCLUSTERED 
(
	[Naam] ASC,
	[Specialisatie] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OuderVoogd]    Script Date: 13-2-2025 17:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OuderVoogd](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Voornaam] [nvarchar](50) NOT NULL,
	[Achternaam] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_OuderVoogd] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Patient]    Script Date: 13-2-2025 17:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patient](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Voornaam] [nvarchar](50) NOT NULL,
	[Achternaam] [nvarchar](50) NOT NULL,
	[OuderVoogd_ID] [int] NOT NULL,
	[TrajectID] [int] NOT NULL,
	[ArtsID] [int] NULL,
 CONSTRAINT [PK_Patient] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Traject]    Script Date: 13-2-2025 17:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Traject](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Naam] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Traject] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_Traject] UNIQUE NONCLUSTERED 
(
	[Naam] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Traject_ZorgMoment]    Script Date: 13-2-2025 17:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Traject_ZorgMoment](
	[TrajectID] [int] NOT NULL,
	[ZorgMomentID] [int] NOT NULL,
	[Volgorde] [int] NOT NULL,
 CONSTRAINT [PK_Traject_ZorgMoment] PRIMARY KEY CLUSTERED 
(
	[TrajectID] ASC,
	[ZorgMomentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ZorgMoment]    Script Date: 13-2-2025 17:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ZorgMoment](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Naam] [nvarchar](50) NOT NULL,
	[Url] [nvarchar](256) NULL,
	[Plaatje] [varbinary](max) NULL,
	[TijdsDuurInMin] [int] NULL,
 CONSTRAINT [PK_ZorgMoment] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_ZorgMoment] UNIQUE NONCLUSTERED 
(
	[Naam] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_Arts] FOREIGN KEY([ArtsID])
REFERENCES [dbo].[Arts] ([ID])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_Arts]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_OuderVoogd] FOREIGN KEY([OuderVoogd_ID])
REFERENCES [dbo].[OuderVoogd] ([ID])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_OuderVoogd]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_Traject] FOREIGN KEY([TrajectID])
REFERENCES [dbo].[Traject] ([ID])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_Traject]
GO
ALTER TABLE [dbo].[Traject_ZorgMoment]  WITH CHECK ADD  CONSTRAINT [FK_Traject_ZorgMoment_Traject] FOREIGN KEY([TrajectID])
REFERENCES [dbo].[Traject] ([ID])
GO
ALTER TABLE [dbo].[Traject_ZorgMoment] CHECK CONSTRAINT [FK_Traject_ZorgMoment_Traject]
GO
ALTER TABLE [dbo].[Traject_ZorgMoment]  WITH CHECK ADD  CONSTRAINT [FK_Traject_ZorgMoment_ZorgMoment] FOREIGN KEY([ZorgMomentID])
REFERENCES [dbo].[ZorgMoment] ([ID])
GO
ALTER TABLE [dbo].[Traject_ZorgMoment] CHECK CONSTRAINT [FK_Traject_ZorgMoment_ZorgMoment]
GO
